# -*- coding: utf-8 -*-
"""ann_tabular_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzk0_khV8_5JKj7t7OysgERp7o1QyqHh

#Project: Personal Health Tracker
Module: ANN for Tabular Data
"""

from google.colab import files
files.upload()

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Model
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

# Load data
df = pd.read_csv("/content/Feature_engineering.csv")

# Select features/target
X = df.drop('HeartDiseaseorAttack', axis=1)
y = df['HeartDiseaseorAttack']
import json
json.dump(list(X.columns), open("feature_names.json", "w"))
print("Feature names saved!")


# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
import joblib
joblib.dump(scaler, "tabular_scaler.pkl")
print("Scaler saved as tabular_scaler.pkl")
inputs = Input(shape=(X_train.shape[1],), name="tabular_input")

x = Dense(128, activation='relu', name="ann_dense_1")(inputs)
x = Dropout(0.3, name="ann_dropout_1")(x)

x = Dense(64, activation='relu', name="ann_dense_2")(x)
x = Dropout(0.2, name="ann_dropout_2")(x)

# Embedding output (used in fusion)
embedding_layer = Dense(32, activation='relu', name="ann_embedding")(x)

# Final prediction layer
output = Dense(1, activation='sigmoid', name="ann_output")(embedding_layer)

ann_model = Model(inputs, output, name="ANN_Model")

ann_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

ann_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=10,
    batch_size=32
)



# Evaluate
ann_model.evaluate(X_test_scaled, y_test)

# Save ANN models
ann_model.save("ann_tabular_model.h5")
embedding_model = Model(inputs, embedding_layer)
embedding_model.save("ann_embedding_model.h5")

print("ANN Model & Embedding Saved.")

print("ANN embedding output shape:", embedding_model.output_shape)